# Generated by Django 5.2.14 on 2026-06-19 15:06
""" Audit fixes for campaigns """

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaign",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("operate_campaign", "Can operate campaigns from the dashboard")
                ],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="status_before_pause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("paused", "Paused"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=30,
            ),
        ),
    ]
