# Generated by Django 5.2.14 on 2026-06-16 04:23
""" Outbox model """

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
        ("email_templates", "0001_initial"),
        ("recipients", "0001_initial"),
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_snapshot", models.TextField()),
                ("body_snapshot", models.TextField()),
                ("body_format", models.CharField(default="text", max_length=10)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("enqueued", "Enqueued"),
                            ("claimed", "Claimed"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("retry_scheduled", "Retry scheduled"),
                            ("failed", "Failed"),
                            ("dead_lettered", "Dead-lettered"),
                            ("requeued", "Requeued"),
                            ("skipped_suppressed", "Skipped suppressed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("locked_by", models.CharField(blank=True, max_length=150)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.CharField(blank=True, max_length=64)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("dead_lettered_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_rows",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "campaign_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbox_rows",
                        to="scheduling.campaignrun",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_rows",
                        to="recipients.recipient",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbox_rows",
                        to="email_templates.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_for", "id"],
            },
        ),
        migrations.CreateModel(
            name="EmailEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("outbox_created", "Outbox created"),
                            ("enqueued", "Enqueued"),
                            ("claimed", "Claimed"),
                            ("send_attempt_started", "Send attempt started"),
                            ("sent", "Sent"),
                            ("retry_scheduled", "Retry scheduled"),
                            ("failed", "Failed"),
                            ("dead_lettered", "Dead-lettered"),
                            ("requeued", "Requeued"),
                            ("skipped_suppressed", "Skipped suppressed"),
                            ("cancelled", "Cancelled"),
                            ("dispatched", "Dispatched"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "campaign_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="scheduling.campaignrun",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_logs",
                        to="recipients.recipient",
                    ),
                ),
                (
                    "outbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="outbox.emailoutbox",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailSendAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("worker_id", models.CharField(blank=True, max_length=150)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("provider_name", models.CharField(max_length=80)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("transient_failure", "Transient failure"),
                            ("permanent_failure", "Permanent failure"),
                        ],
                        max_length=30,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=80)),
                ("error_message", models.TextField(blank=True)),
                (
                    "provider_response_metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "outbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="outbox.emailoutbox",
                    ),
                ),
            ],
            options={
                "ordering": ["outbox", "attempt_number"],
            },
        ),
        migrations.AddIndex(
            model_name="emailoutbox",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="outbox_emai_status_fbb825_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailoutbox",
            index=models.Index(
                fields=["campaign", "status"], name="outbox_emai_campaig_78436b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailoutbox",
            index=models.Index(
                fields=["campaign_run", "recipient"],
                name="outbox_emai_campaig_d60ba3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaileventlog",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="outbox_emai_event_t_f94e35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaileventlog",
            index=models.Index(
                fields=["outbox", "created_at"], name="outbox_emai_outbox__f22e5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaileventlog",
            index=models.Index(
                fields=["campaign", "created_at"], name="outbox_emai_campaig_dbaa42_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="emailsendattempt",
            constraint=models.UniqueConstraint(
                fields=("outbox", "attempt_number"), name="unique_outbox_attempt_number"
            ),
        ),
    ]
