# Generated by Django 5.2.14 on 2026-06-18 02:25
""" Required variables snapshot field """

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailoutbox",
            name="required_variables_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
