# Generated by Django 5.2.14 on 2026-06-19 15:22
""" Locked at index """

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_audit_fixes"),
        ("email_templates", "0001_initial"),
        ("outbox", "0002_emailoutbox_required_variables_snapshot"),
        ("recipients", "0001_initial"),
        ("scheduling", "0002_audit_fixes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailoutbox",
            index=models.Index(
                fields=["status", "locked_at"], name="outbox_emai_status_fdbf9c_idx"
            ),
        ),
    ]
