# Generated by Django 5.2.14 on 2026-06-19 15:40
""" Campaign completed event """

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0003_locked_at_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaileventlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("outbox_created", "Outbox created"),
                    ("enqueued", "Enqueued"),
                    ("claimed", "Claimed"),
                    ("send_attempt_started", "Send attempt started"),
                    ("sent", "Sent"),
                    ("retry_scheduled", "Retry scheduled"),
                    ("failed", "Failed"),
                    ("dead_lettered", "Dead-lettered"),
                    ("requeued", "Requeued"),
                    ("skipped_suppressed", "Skipped suppressed"),
                    ("cancelled", "Cancelled"),
                    ("dispatched", "Dispatched"),
                    ("campaign_completed", "Campaign completed"),
                ],
                max_length=50,
            ),
        ),
    ]
