-- Email Automation reference schema
-- PostgreSQL-style schema generated from the current Django model layer.
-- This is intended for review/documentation, not as a replacement for Django migrations.

CREATE TABLE email_templates_emailtemplate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    subject_template TEXT NOT NULL,
    body_template TEXT NOT NULL,
    body_format VARCHAR(10) NOT NULL DEFAULT 'text' CHECK (body_format IN ('text', 'html')),
    required_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recipients_recipient (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL DEFAULT '',
    custom_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
    subscribed BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recipients_recipientlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    segment_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE recipients_recipientlist_recipients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipientlist_id BIGINT NOT NULL REFERENCES recipients_recipientlist(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES recipients_recipient(id) ON DELETE CASCADE,
    UNIQUE (recipientlist_id, recipient_id)
);

CREATE TABLE recipients_suppressionentry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    reason VARCHAR(255) NOT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'unsubscribe', 'import', 'bounce', 'test')),
    created_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE campaigns_campaign (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    template_id BIGINT NOT NULL REFERENCES email_templates_emailtemplate(id) ON DELETE RESTRICT,
    recipient_list_id BIGINT NOT NULL REFERENCES recipients_recipientlist(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'paused', 'active', 'completed', 'cancelled')),
    status_before_pause VARCHAR(30) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE scheduling_campaignschedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns_campaign(id) ON DELETE CASCADE,
    schedule_type VARCHAR(20) NOT NULL CHECK (schedule_type IN ('one_time', 'recurring')),
    send_at TIMESTAMPTZ NULL,
    cron_expression VARCHAR(80) NOT NULL DEFAULT '',
    interval_every INTEGER NULL CHECK (interval_every > 0),
    interval_period VARCHAR(20) NOT NULL DEFAULT '' CHECK (interval_period IN ('', 'minutes', 'hours', 'days')),
    timezone_name VARCHAR(80) NOT NULL DEFAULT 'UTC',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_run_at TIMESTAMPTZ NULL,
    next_run_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE scheduling_campaignrun (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns_campaign(id) ON DELETE CASCADE,
    schedule_id BIGINT NOT NULL REFERENCES scheduling_campaignschedule(id) ON DELETE CASCADE,
    run_key VARCHAR(255) NOT NULL UNIQUE,
    scheduled_for TIMESTAMPTZ NOT NULL,
    generated_at TIMESTAMPTZ NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'generating_outbox', 'outbox_generated', 'dispatching', 'dispatched', 'completed', 'failed', 'cancelled')),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT unique_schedule_occurrence UNIQUE (schedule_id, scheduled_for)
);

CREATE TABLE outbox_emailoutbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES campaigns_campaign(id) ON DELETE CASCADE,
    campaign_run_id BIGINT NOT NULL REFERENCES scheduling_campaignrun(id) ON DELETE CASCADE,
    recipient_id BIGINT NOT NULL REFERENCES recipients_recipient(id) ON DELETE RESTRICT,
    template_id BIGINT NOT NULL REFERENCES email_templates_emailtemplate(id) ON DELETE RESTRICT,
    subject_snapshot TEXT NOT NULL,
    body_snapshot TEXT NOT NULL,
    required_variables_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
    body_format VARCHAR(10) NOT NULL DEFAULT 'text',
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'enqueued', 'claimed', 'sending', 'sent', 'retry_scheduled', 'failed', 'dead_lettered', 'requeued', 'skipped_suppressed', 'cancelled')),
    scheduled_for TIMESTAMPTZ NOT NULL,
    next_attempt_at TIMESTAMPTZ NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts >= 0),
    locked_by VARCHAR(150) NOT NULL DEFAULT '',
    locked_at TIMESTAMPTZ NULL,
    claim_token VARCHAR(64) NOT NULL DEFAULT '',
    lock_version INTEGER NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
    celery_task_id VARCHAR(255) NOT NULL DEFAULT '',
    enqueued_at TIMESTAMPTZ NULL,
    started_at TIMESTAMPTZ NULL,
    sent_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    dead_lettered_at TIMESTAMPTZ NULL,
    last_error TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX outbox_emailoutbox_status_next_attempt_at_idx ON outbox_emailoutbox (status, next_attempt_at);
CREATE INDEX outbox_emailoutbox_status_locked_at_idx ON outbox_emailoutbox (status, locked_at);
CREATE INDEX outbox_emailoutbox_campaign_status_idx ON outbox_emailoutbox (campaign_id, status);
CREATE INDEX outbox_emailoutbox_campaign_run_recipient_idx ON outbox_emailoutbox (campaign_run_id, recipient_id);

CREATE TABLE outbox_emailsendattempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id BIGINT NOT NULL REFERENCES outbox_emailoutbox(id) ON DELETE CASCADE,
    attempt_number INTEGER NOT NULL CHECK (attempt_number >= 0),
    worker_id VARCHAR(150) NOT NULL DEFAULT '',
    celery_task_id VARCHAR(255) NOT NULL DEFAULT '',
    provider_name VARCHAR(80) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    result VARCHAR(30) NOT NULL DEFAULT '' CHECK (result IN ('', 'success', 'transient_failure', 'permanent_failure')),
    error_code VARCHAR(80) NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    provider_response_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT unique_outbox_attempt_number UNIQUE (outbox_id, attempt_number)
);

CREATE TABLE outbox_emaileventlog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL CHECK (event_type IN ('scheduled', 'outbox_created', 'enqueued', 'claimed', 'send_attempt_started', 'sent', 'retry_scheduled', 'failed', 'dead_lettered', 'requeued', 'skipped_suppressed', 'cancelled', 'dispatched', 'campaign_completed', 'operator_action')),
    campaign_id BIGINT NULL REFERENCES campaigns_campaign(id) ON DELETE CASCADE,
    campaign_run_id BIGINT NULL REFERENCES scheduling_campaignrun(id) ON DELETE CASCADE,
    outbox_id BIGINT NULL REFERENCES outbox_emailoutbox(id) ON DELETE CASCADE,
    recipient_id BIGINT NULL REFERENCES recipients_recipient(id) ON DELETE SET NULL,
    message TEXT NOT NULL DEFAULT '',
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX outbox_emaileventlog_event_type_created_at_idx ON outbox_emaileventlog (event_type, created_at);
CREATE INDEX outbox_emaileventlog_outbox_created_at_idx ON outbox_emaileventlog (outbox_id, created_at);
CREATE INDEX outbox_emaileventlog_campaign_created_at_idx ON outbox_emaileventlog (campaign_id, created_at);
