# Generated by Django 5.2.14 on 2026-06-16 04:23
""" Campaign schedule model """

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[("one_time", "One time"), ("recurring", "Recurring")],
                        max_length=20,
                    ),
                ),
                (
                    "send_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="UTC time for one-time schedules or first recurring run.",
                        null=True,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Five-field cron expression for recurring schedules.",
                        max_length=80,
                    ),
                ),
                ("interval_every", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "interval_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timezone_name", models.CharField(default="UTC", max_length=80)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_at", "send_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_key", models.CharField(max_length=255, unique=True)),
                ("scheduled_for", models.DateTimeField()),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating_outbox", "Generating outbox"),
                            ("outbox_generated", "Outbox generated"),
                            ("dispatching", "Dispatching"),
                            ("dispatched", "Dispatched"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="scheduling.campaignschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule", "scheduled_for"),
                        name="unique_schedule_occurrence",
                    )
                ],
            },
        ),
    ]
