# Generated by Django 5.2.14 on 2026-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignschedule",
            name="timezone_name",
            field=models.CharField(
                default="UTC",
                help_text="Display-only timezone for operator UI. Dispatch always uses UTC.",
                max_length=80,
            ),
        ),
    ]
